add_executable(orbit_engine_core_test
  core_test.cpp
)

target_link_libraries(orbit_engine_core_test PRIVATE orbit_engine_core)

add_test(NAME orbit_engine_core_test COMMAND orbit_engine_core_test)

add_executable(orbit_engine_oep_test
  oep_test.cpp
)

target_link_libraries(orbit_engine_oep_test PRIVATE orbit_engine_core)

add_test(NAME orbit_engine_oep_test COMMAND orbit_engine_oep_test)

add_executable(orbit_engine_numerical_test
  numerical_test.cpp
)

target_link_libraries(orbit_engine_numerical_test PRIVATE orbit_engine_core)

add_test(NAME orbit_engine_numerical_test COMMAND orbit_engine_numerical_test)

add_executable(orbit_engine_numerical_operation_test
  numerical_operation_test.cpp
)

target_link_libraries(orbit_engine_numerical_operation_test PRIVATE orbit_engine_core)

add_test(NAME orbit_engine_numerical_operation_test COMMAND orbit_engine_numerical_operation_test)

add_executable(orbit_engine_force_test
  force_test.cpp
)

target_link_libraries(orbit_engine_force_test PRIVATE orbit_engine_core)

add_test(NAME orbit_engine_force_test COMMAND orbit_engine_force_test)

add_executable(orbit_engine_numerical_motion_test
  numerical_motion_test.cpp
)

target_link_libraries(orbit_engine_numerical_motion_test PRIVATE orbit_engine_core)

add_test(NAME orbit_engine_numerical_motion_test COMMAND orbit_engine_numerical_motion_test)

add_executable(orbit_engine_coupled_test
  coupled_test.cpp
)

target_link_libraries(orbit_engine_coupled_test PRIVATE orbit_engine_core)

add_test(NAME orbit_engine_coupled_test COMMAND orbit_engine_coupled_test)

add_executable(orbit_engine_coupled_operation_test
  coupled_operation_test.cpp
)

target_link_libraries(orbit_engine_coupled_operation_test PRIVATE orbit_engine_core)

add_test(NAME orbit_engine_coupled_operation_test COMMAND orbit_engine_coupled_operation_test)

add_executable(orbit_engine_scheduler_test
  scheduler_test.cpp
)

target_link_libraries(orbit_engine_scheduler_test PRIVATE orbit_engine_core)

add_test(NAME orbit_engine_scheduler_test COMMAND orbit_engine_scheduler_test)

add_executable(orbit_engine_advance_test
  advance_test.cpp
)

target_link_libraries(orbit_engine_advance_test PRIVATE orbit_engine_core)

add_test(NAME orbit_engine_advance_test COMMAND orbit_engine_advance_test)
