export interface LightingInspectorTuning {
  readonly exposureMultiplier: number;
  readonly surfaceRadianceGain: number;
  readonly atmosphereRayleighGain: number;
  readonly atmosphereMieGain: number;
  readonly atmosphereAbsorptionGain: number;
  readonly atmosphereOpticalDepthGain: number;
  readonly atmosphereAnisotropyScale: number;
  readonly atmosphereShellDisplayGain: number;
  readonly atmosphereSurfaceCompositeGain: number;
  readonly atmosphereLimbGain: number;
  readonly bloomStrength: number;
  readonly bloomRadius: number;
  readonly bloomCompositeGain: number;
  readonly bloomSurfaceWeight: number;
  readonly bloomSourceOpticalDepthCap: number;
  readonly bloomSourceMieChromaGain: number;
  readonly bloomSourceRayleighReduction: number;
}

export const DEFAULT_LIGHTING_INSPECTOR_TUNING: LightingInspectorTuning = Object.freeze({
  exposureMultiplier: 1,
  surfaceRadianceGain: 1.6,
  atmosphereRayleighGain: 1,
  atmosphereMieGain: 1,
  atmosphereAbsorptionGain: 1,
  atmosphereOpticalDepthGain: 1,
  atmosphereAnisotropyScale: 1,
  atmosphereShellDisplayGain: 3.5,
  atmosphereSurfaceCompositeGain: 0.38,
  atmosphereLimbGain: 1.25,
  bloomStrength: 0.28,
  bloomRadius: 0.85,
  bloomCompositeGain: 0.75,
  bloomSurfaceWeight: 0.16,
  bloomSourceOpticalDepthCap: 1.25,
  bloomSourceMieChromaGain: 4,
  bloomSourceRayleighReduction: 0.9,
});

interface InspectorControl {
  readonly key: keyof LightingInspectorTuning;
  readonly label: string;
  readonly help: string;
  readonly min: number;
  readonly max: number;
  readonly step: number;
}

const STORAGE_KEY = "orbit-engine-demo-lighting-inspector-v2";

const CONTROL_GROUPS: readonly Readonly<{
  readonly title: string;
  readonly description: string;
  readonly controls: readonly InspectorControl[];
}>[] = Object.freeze([
  {
    title: "Surface / camera",
    description: "Changes display brightness only; stellar irradiance and orbital physics stay untouched.",
    controls: [
      { key: "exposureMultiplier", label: "Exposure multiplier", help: "Multiplies the automatic focus exposure after the physical 1/r² illumination has been resolved.", min: 0.2, max: 3, step: 0.05 },
      { key: "surfaceRadianceGain", label: "Surface radiance gain", help: "Global presentation gain applied to reflected planetary surface radiance before ACES tone mapping.", min: 0.2, max: 3, step: 0.05 },
    ],
  },
  {
    title: "Atmosphere transport",
    description: "Debug multipliers on the resolved atmosphere coefficients. They are global and are restored after each render.",
    controls: [
      { key: "atmosphereRayleighGain", label: "Rayleigh gain", help: "Boosts molecular scattering. Higher values strengthen wavelength-dependent blue/cyan scattering.", min: 0, max: 4, step: 0.05 },
      { key: "atmosphereMieGain", label: "Mie / aerosol gain", help: "Boosts aerosol/dust scattering. This is the important warm-haze control for atmospheres such as Mars.", min: 0, max: 6, step: 0.05 },
      { key: "atmosphereAbsorptionGain", label: "Absorption gain", help: "Strengthens wavelength-dependent atmospheric absorption; higher values remove more light along long paths.", min: 0, max: 4, step: 0.05 },
      { key: "atmosphereOpticalDepthGain", label: "Optical depth", help: "Scales total atmospheric path density/opacity without changing the authored RGB coefficient ratios.", min: 0.1, max: 4, step: 0.05 },
      { key: "atmosphereAnisotropyScale", label: "Mie anisotropy scale", help: "Scales the authored aerosol forward-scattering anisotropy. 0 makes the anisotropic component isotropic; 1 uses the dataset value.", min: 0, max: 1.5, step: 0.05 },
    ],
  },
  {
    title: "Atmosphere shell presentation",
    description: "These are the three shader presentation gains that were previously hard-coded and repeatedly tuned during the atmosphere fixes.",
    controls: [
      { key: "atmosphereShellDisplayGain", label: "Shell display gain", help: "Brightness of atmosphere pixels outside the opaque planet silhouette before bloom.", min: 0, max: 10, step: 0.1 },
      { key: "atmosphereSurfaceCompositeGain", label: "Surface composite gain", help: "Brightness of front-side atmosphere composited over the visible planet disk. Too high washes out textures and drives the limb white.", min: 0, max: 2, step: 0.02 },
      { key: "atmosphereLimbGain", label: "Limb gain", help: "Extra brightness for long tangent paths near the atmospheric rim. Higher values emphasize the thin outline before bloom.", min: 1, max: 4, step: 0.05 },
    ],
  },
  {
    title: "Selective atmosphere bloom",
    description: "Only atmosphere shells enter this post-process; planet surfaces, guides and selection marks are excluded.",
    controls: [
      { key: "bloomStrength", label: "Bloom strength", help: "Strength of the blurred atmosphere source generated by UnrealBloomPass.", min: 0, max: 0.8, step: 0.01 },
      { key: "bloomRadius", label: "Bloom radius", help: "Width/softness of the bloom kernel. Higher values spread the halo farther outside the silhouette.", min: 0, max: 1, step: 0.01 },
      { key: "bloomCompositeGain", label: "Bloom composite gain", help: "Final linear-HDR multiplier when the blurred atmosphere is composited back into the scene.", min: 0, max: 2, step: 0.02 },
      { key: "bloomSurfaceWeight", label: "Bloom on planet disk", help: "How much bloom is allowed over already-bright surface pixels. Keep low to avoid washed-out planets.", min: 0, max: 0.5, step: 0.01 },
      { key: "bloomSourceOpticalDepthCap", label: "Bloom optical-depth cap", help: "Presentation-only cap used while rendering the off-screen bloom source so dense atmospheres do not extinguish their own halo.", min: 0.1, max: 4, step: 0.05 },
      { key: "bloomSourceMieChromaGain", label: "Bloom Mie color emphasis", help: "Emphasizes spectrally colored aerosol scattering in the bloom source; useful for diagnosing warm dust/haze color.", min: 0, max: 8, step: 0.1 },
      { key: "bloomSourceRayleighReduction", label: "Bloom Rayleigh suppression", help: "Suppresses Rayleigh in proportion to aerosol color contrast so colored Mie haze can dominate the halo instead of turning white/blue.", min: 0, max: 1, step: 0.02 },
    ],
  },
]);

function clamp(value: number, control: InspectorControl): number {
  if (!Number.isFinite(value)) return DEFAULT_LIGHTING_INSPECTOR_TUNING[control.key];
  return Math.min(control.max, Math.max(control.min, value));
}

function loadStoredTuning(): LightingInspectorTuning {
  try {
    const raw = globalThis.localStorage?.getItem(STORAGE_KEY);
    if (raw === null || raw === undefined) return { ...DEFAULT_LIGHTING_INSPECTOR_TUNING };
    const parsed = JSON.parse(raw) as Partial<Record<keyof LightingInspectorTuning, unknown>>;
    const next = { ...DEFAULT_LIGHTING_INSPECTOR_TUNING } as Record<keyof LightingInspectorTuning, number>;
    for (const group of CONTROL_GROUPS) {
      for (const control of group.controls) {
        const candidate = parsed[control.key];
        if (typeof candidate === "number") next[control.key] = clamp(candidate, control);
      }
    }
    return next;
  } catch {
    return { ...DEFAULT_LIGHTING_INSPECTOR_TUNING };
  }
}

function formatValue(value: number, step: number): string {
  const decimals = step >= 1 ? 0 : step >= 0.1 ? 1 : 2;
  return value.toFixed(decimals);
}

function ensureInspectorStyles(): void {
  if (document.getElementById("lighting-inspector-styles") !== null) return;
  const style = document.createElement("style");
  style.id = "lighting-inspector-styles";
  style.textContent = `
#lighting-inspector .lighting-inspector-intro { margin: 0 0 12px; color: var(--muted, #94a3b8); font-size: 0.78rem; line-height: 1.45; }
#lighting-inspector .lighting-inspector-group { border-top: 1px solid rgba(148,163,184,.16); padding-top: 12px; margin-top: 12px; }
#lighting-inspector .lighting-inspector-group:first-of-type { border-top: 0; margin-top: 0; padding-top: 0; }
#lighting-inspector .lighting-inspector-group h3 { margin: 0 0 3px; font-size: .82rem; }
#lighting-inspector .lighting-inspector-group > p { margin: 0 0 10px; color: var(--muted, #94a3b8); font-size: .7rem; line-height: 1.35; }
#lighting-inspector .lighting-inspector-control { display: grid; grid-template-columns: minmax(0,1fr) auto; gap: 3px 8px; margin-bottom: 10px; }
#lighting-inspector .lighting-inspector-control label { font-size: .74rem; font-weight: 600; }
#lighting-inspector .lighting-inspector-control output { min-width: 3.2rem; text-align: right; font: 600 .7rem/1.2 ui-monospace, SFMono-Regular, Menlo, monospace; color: #dbeafe; }
#lighting-inspector .lighting-inspector-control input[type=range] { grid-column: 1 / -1; width: 100%; margin: 2px 0 0; accent-color: #60a5fa; }
#lighting-inspector .lighting-inspector-control small { grid-column: 1 / -1; color: var(--muted, #94a3b8); font-size: .65rem; line-height: 1.3; }
#lighting-inspector .lighting-inspector-actions { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 12px; }
#lighting-inspector .lighting-inspector-copy-status { margin: 8px 0 0; min-height: 1em; font-size: .68rem; color: #93c5fd; white-space: pre-wrap; }
`;
  document.head.append(style);
}

export interface LightingInspectorHandle {
  readonly tuning: () => LightingInspectorTuning;
  dispose(): void;
}

export function installLightingInspector(
  onChange: (tuning: LightingInspectorTuning) => void,
): LightingInspectorHandle {
  ensureInspectorStyles();
  document.getElementById("lighting-inspector")?.remove();
  document.querySelector<HTMLButtonElement>('#control-nav button[data-target="lighting-inspector"]')?.remove();

  let current = loadStoredTuning();
  const section = document.createElement("section");
  section.className = "panel-section";
  section.id = "lighting-inspector";
  section.tabIndex = -1;
  section.setAttribute("aria-labelledby", "lighting-inspector-heading");
  section.innerHTML = `
    <div class="section-heading">
      <div>
        <p class="section-kicker">Debug presentation</p>
        <h2 id="lighting-inspector-heading">Lighting inspector</h2>
      </div>
      <span class="scenario-badge">Live</span>
    </div>
    <p class="lighting-inspector-intro">Temporary runtime controls for the shared planetary lighting pipeline. Values are global, persist locally across reloads, and do not modify OrbitEngine physics or body datasets.</p>
  `;

  const inputs = new Map<keyof LightingInspectorTuning, HTMLInputElement>();
  const outputs = new Map<keyof LightingInspectorTuning, HTMLOutputElement>();

  const emit = (): void => {
    try {
      globalThis.localStorage?.setItem(STORAGE_KEY, JSON.stringify(current));
    } catch {
      // Storage is convenience only; rendering must not depend on it.
    }
    onChange(Object.freeze({ ...current }));
  };

  for (const group of CONTROL_GROUPS) {
    const groupElement = document.createElement("div");
    groupElement.className = "lighting-inspector-group";
    const heading = document.createElement("h3");
    heading.textContent = group.title;
    const description = document.createElement("p");
    description.textContent = group.description;
    groupElement.append(heading, description);

    for (const control of group.controls) {
      const row = document.createElement("div");
      row.className = "lighting-inspector-control";
      const label = document.createElement("label");
      const id = `lighting-inspector-${control.key}`;
      label.htmlFor = id;
      label.textContent = control.label;
      const output = document.createElement("output");
      output.setAttribute("for", id);
      output.value = formatValue(current[control.key], control.step);
      const input = document.createElement("input");
      input.id = id;
      input.type = "range";
      input.min = String(control.min);
      input.max = String(control.max);
      input.step = String(control.step);
      input.value = String(current[control.key]);
      input.setAttribute("aria-describedby", `${id}-help`);
      const help = document.createElement("small");
      help.id = `${id}-help`;
      help.textContent = control.help;
      input.addEventListener("input", () => {
        const value = clamp(Number(input.value), control);
        current = Object.freeze({ ...current, [control.key]: value });
        output.value = formatValue(value, control.step);
        emit();
      });
      inputs.set(control.key, input);
      outputs.set(control.key, output);
      row.append(label, output, input, help);
      groupElement.append(row);
    }
    section.append(groupElement);
  }

  const actions = document.createElement("div");
  actions.className = "lighting-inspector-actions";
  const reset = document.createElement("button");
  reset.className = "secondary-button";
  reset.type = "button";
  reset.textContent = "Reset defaults";
  const copy = document.createElement("button");
  copy.className = "secondary-button";
  copy.type = "button";
  copy.textContent = "Copy values";
  const status = document.createElement("p");
  status.className = "lighting-inspector-copy-status";
  status.setAttribute("aria-live", "polite");

  reset.addEventListener("click", () => {
    current = { ...DEFAULT_LIGHTING_INSPECTOR_TUNING };
    for (const group of CONTROL_GROUPS) {
      for (const control of group.controls) {
        inputs.get(control.key)!.value = String(current[control.key]);
        outputs.get(control.key)!.value = formatValue(current[control.key], control.step);
      }
    }
    emit();
    status.textContent = "Defaults restored.";
  });

  copy.addEventListener("click", async () => {
    const text = JSON.stringify(current, null, 2);
    try {
      await navigator.clipboard.writeText(text);
      status.textContent = "Values copied to clipboard.";
    } catch {
      status.textContent = text;
    }
  });
  actions.append(reset, copy);
  section.append(actions, status);

  const viewSection = document.getElementById("view-section");
  if (viewSection !== null) viewSection.insertAdjacentElement("afterend", section);
  else document.getElementById("panel-content")?.append(section);

  const nav = document.getElementById("control-nav");
  if (nav !== null) {
    const button = document.createElement("button");
    button.type = "button";
    button.dataset.target = "lighting-inspector";
    button.setAttribute("aria-controls", "lighting-inspector");
    button.textContent = "Lighting";
    button.addEventListener("click", () => {
      nav.querySelectorAll("button[data-target]").forEach((candidate) => candidate.removeAttribute("aria-current"));
      button.setAttribute("aria-current", "true");
      section.scrollIntoView({ block: "start", behavior: "smooth" });
      section.focus({ preventScroll: true });
    });
    const viewButton = nav.querySelector<HTMLButtonElement>('button[data-target="view-section"]');
    if (viewButton?.nextSibling !== null && viewButton?.nextSibling !== undefined) nav.insertBefore(button, viewButton.nextSibling);
    else nav.append(button);
  }

  emit();

  return {
    tuning: () => Object.freeze({ ...current }),
    dispose() {
      section.remove();
      document.querySelector<HTMLButtonElement>('#control-nav button[data-target="lighting-inspector"]')?.remove();
    },
  };
}
